version: '3'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=api.celery_worker
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A api.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
